In [1]:
import numpy as np
import pandas as pd


#### Write a function so that the columns of the output matrix are powers of the input
vector.


In [2]:
def generate_vandermatrix(in_vect, n , increasing = False):
    if not increasing:
        result_matrix = np.array([x**(n-i-1) for x in in_vect for i in range(n)]).reshape(in_vect.size,n)
    elif increasing:
        result_matrix = np.array([x**i for x in in_vector for i in range(n)]).reshape(in_vect.size,n)
    
    return result_matrix
    
in_vector =np.array([2,6,9])
no_columns = 3
result_matrix_Desc = generate_vandermatrix(in_vector, no_columns , False)
result_matrix_Asc = generate_vandermatrix(in_vector, no_columns , True)
print("The input array is:",in_vector,"\n")
print("Number of columns in output matrix:",no_columns,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",result_matrix_Desc,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",result_matrix_Asc,"\n")



            

The input array is: [2 6 9] 

Number of columns in output matrix: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 4  2  1]
 [36  6  1]
 [81  9  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  2  4]
 [ 1  6 36]
 [ 1  9 81]] 



#####  Write a function to find moving average in an array over a window . Test it over [3, 5, 7, 2, 8, 10, 11, 65,                              72, 81, 99, 100, 150] and window of 3

In [3]:
def moving_average(input_array, k=3) :
    input_array_shape = input_array.shape[0]
    
    #Create a vector of zeroes with the shape as n-k+1
    
    out_array_moving_avg = np.zeros(input_array_shape - k + 1)
    
    # Iterate over the input array. While doing so, for every element, get the next k elements through slicing, 
    # computer their mean and add to the output array.
    
    for i in range(k, input_array_shape + 1):
        out_array_moving_avg[i-k] = input_array[i-k:i].mean()
    
    return out_array_moving_avg   


a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
win_size = 3
moving_average_arr = moving_average(a, win_size)

print("The input sequence is =", a, "\n")
print("The moving average of the sequence with the rolling window size", win_size, "is =\n", moving_average_arr, "\n")
print("The moving average sequence should have", a.shape[0] - win_size + 1, "values.\n")
print("The moving average sequence has", moving_average_arr.shape[0], "values.")

The input sequence is = [  3   5   7   2   8  10  11  65  72  81  99 100 150] 

The moving average of the sequence with the rolling window size 3 is =
 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333] 

The moving average sequence should have 11 values.

The moving average sequence has 11 values.
